# Generated by Django 6.0.5 on 2026-05-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeprofile_is_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='active_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='idle_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='productivity_percentage',
            field=models.FloatField(default=0),
        ),
    ]
