# Generated by Django 6.0.5 on 2026-06-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employeeprofile_active_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='break_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='is_on_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='total_break_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
