# Generated by Django 6.0.5 on 2026-05-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='is_warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
